name = input("enter your name:")
surname = input("enter your surname:")
age = input("enter your age:")
number1 = input("enter your number:")
number2 = input("enter your number2:")
print(type(name))
print(type(surname))
print(type(age))
print(type(number1))
print(type(number2))

